name: vue-tiptap-example

services:
  ### Keycloak Service ###
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    container_name: tiptap-example-keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD:-admin}
    ports:
      - 8080:8080
    networks:
      - local_network
    volumes:
      - "./${KC_IMPORT_FILE:-default-realm.json}:/opt/keycloak/data/import/${KC_IMPORT_FILE:-default-realm.json}"

  ### Backend Service ###
  backend:
    container_name: tiptap-example-backend
    build:
      context: ./backend
      target: ${TARGET:-debug}
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - backend/node_modules
    ports:
      - 1234:1234
    networks:
      - local_network

  ### Frontend Service ###
  frontend:
    container_name: tiptap-example-frontend
    build:
      context: ./frontend
      target: ${TARGET:-debug}
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - frontend/node_modules
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost}
      VITE_HOCUSPOCUS_WS_BASE_URL: ${HOCUSPOCUS_WS_BASE_URL:-ws://localhost:1234}
      VITE_KC_URL: ${KC_URL:-http://localhost:8080}
    ports:
      - 3000:3000
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
