name: vue-tiptap-example

services:
  ### Backend Service ###
  backend:
    container_name: tiptap-example-backend
    build:
      context: ./backend
      target: ${TARGET:-debug}
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - backend/node_modules
    ports:
      - 1234:1234
    networks:
      - local_network

  ### Frontend Service ###
  frontend:
    container_name: tiptap-example-frontend
    build:
      context: ./frontend
      target: ${TARGET:-debug}
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - frontend/node_modules
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost}
      VITE_HOCUSPOCUS_WS_IP: ${HOCUSPOCUS_WS_IP:-127.0.0.1}
    ports:
      - 3000:3000
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
